name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db_card:
        image: postgres:14
        env:
          POSTGRES_DB: app
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: dock123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U docker -d app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          extensions: intl, pdo_pgsql, pdo_sqlite
          ini-values: date.timezone=UTC

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-8.3-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.3-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Run tests
        run: composer test
        env:
          YII_ENV: test
